### ISSUE TITLE
CMake scripts and Windows compatibilty

### ISSUE THREAD

**Issue by alex85k** [joto/osmium#71]
I am currently working on Windows compatibility of Osmium in my fork. The goal is to support MinGW 32/64 and MSVC. (Certain features can be disabled by #ifdefs before someone rewrite them in native code).

Currently I have CMake build scripts and slightly patched code working at least for Mingw32 and Ubuntu, planning also to support Visual Studio. Only disabled features for now is execute() method in osmfile.hpp and mmap_anon storage.

CMake file support installation and automatic testing,  missig features for now are valgrind and cppcheck.

Can you please give me some advice on how to make the code suitable for future inclusion?
https://github.com/alex85k/osmium/tree/mingw

For example, CMake generates the makefiles that overwrite existing ones. They are not to be committed (we want to keep old building system too).

**Comment by joto** [comment]
I am closing this issue. This will not be fixed in osmium any more, but the newer [libosmium](http://osmcode/libosmium) works fine on Windows.
