### ISSUE TITLE
Support .gz and .bz2 files without using pipes?

### ISSUE THREAD

**Issue by alex85k** [joto/osmium#73]
Currently to operate with osm.gz and osm.bz2 Osmium invokes console utilities.
This is almost the feature that is hard no implement on non-Unix system (almost the last unsupported one). 

Is there any possibilty to use bzip2 and zlib ?  This should also increase performance...

**Comment by joto** [comment]
This has been implemented in [libosmium](http://osmcode.org/libosmium). This version of osmium will not get that feature.
